---
- name: "Déployer Nginx custom sur k3d"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Créer le namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: web

    - name: Déployer l'application
      kubernetes.core.k8s:
        state: present
        namespace: web
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: nginx-custom
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: nginx
            template:
              metadata:
                labels:
                  app: nginx
              spec:
                containers:
                  - name: nginx
                    image: custom-nginx:latest
                    imagePullPolicy: IfNotPresent
                    ports:
                      - containerPort: 80

    - name: Exposer le service (LoadBalancer)
      kubernetes.core.k8s:
        state: present
        namespace: web
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: nginx-service
          spec:
            type: LoadBalancer
            selector:
              app: nginx
            ports:
              - port: 80
                targetPort: 80